# Generated by Django 5.0.7 on 2024-07-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_two_auth', models.BooleanField(default=False)),
                ('additional_email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('public_url', models.URLField(max_length=255)),
                ('web_url', models.URLField(blank=True, max_length=255)),
                ('twitter_url', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('background_img', models.ImageField(blank=True, upload_to='users/background-images/')),
                ('profile_content', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
