# Generated by Django 5.0.7 on 2024-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameexpuser',
            name='twitter_login',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
