# Generated by Django 5.0.7 on 2024-07-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameexp_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameExpUser',
        ),
    ]
